# Generated by Django 2.0.4 on 2018-05-15 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('X', models.IntegerField(max_length=40)),
                ('Y', models.IntegerField(max_length=40)),
            ],
        ),
    ]
